file = keystore_prod.jks
storePassword=vitalself!23
keyPassword=vitalself!23
keyAlias=key0
storeFile=keystore/keystore_prod.jks
DEBUG_BASE_URL=https://vitalself.nuverse.in
RELEASE_BASE_URL=https://vitalself.nuverse.in

app_version= v3.0
app_version_debug= d_v3.0

version_code= 3




